# Permalinks
permalink: pretty

# Setup
title: ANR EPERVIER

future: true

url: https://XLIM-Perception.github.io
baseurl: /anr-epervier
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# About/contact
author:
  name: EPERVIER
  url: https://XLIM-Perception.github.io
  email:epervier-anr@ml.univ-poitiers.fr

# Custom vars
version: 1.0.0

# Navigation
nav_links:
  - title: "Home"
    url: "/"
  - title: "Partenaire"
    url: "/01_partenaire/"
  - title: "Objectifs"
    url: "/02_objectifs/"
  - title: "Actualit√©s"
    url: "/03_actualites/"
  - title: "Offre de Postes"
    url: "/04_offre-de-postes/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
